apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  type: NodePort
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: 30008
  selector:
    app: simp
    type: backend